version: '2'
services:
  odoo:
    image: odoo
    volumes:
    - odoo-web-data:/var/lib/odoo
    - ./config:/etc/odoo
    - ./addons:/mnt/extra-addons
    links:
    - db:db
    ports:
    - 8069:8069/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: type=application
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: odooRJR2407$
      POSTGRES_USER: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - odoo-db-data:/var/lib/postgresql/data/pgdata
    labels:
      io.rancher.scheduler.affinity:host_label: type=database
volumes:
  odoo-web-data: /srv/odoo/web_data
  odoo-db-data: /srv/odoo/pg_data