odoo:
  image: odoo:10.0
  ports:
    - "8069:8069"
  links:
    - db
  volumes:
    - /srv/odoo/web_data:/var/lib/odoo
    - /srv/odoo/web_data/config:/etc/odoo
    - /srv/odoo/web_data/addons:/mnt/extra-addons    
db:
  image: postgres
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odooDBArjr2407$
    - PGDATA=/var/lib/postgresql/data/pgdata
  volumes:
    - /srv/odoo/postgresql:/var/lib/postgresql/data/pgdata